version: '3.8'

services:
  nginx-proxy-go:
    build: .
    container_name: nginx-proxy-go-dev
    environment:
      NGINX_CONF_DIR: /etc/nginx
      CHALLENGE_DIR: /tmp/acme-challenges
      SSL_DIR: /etc/ssl
      HOSTNAME: nginx-proxy-go-dev
      GO_DEBUG_ENABLE: 'false'
      GO_DEBUG_PORT: '2345'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nginx-proxy-go-nginx:/etc/nginx
      - nginx-proxy-go-ssl:/etc/ssl
      - nginx-proxy-go-acme:/tmp/acme-challenges
    ports:
      - "2345:2345" # Delve debug port
      - "80:80"
      - "443:443"
    restart: unless-stopped

volumes:
  nginx-proxy-go-nginx:
  nginx-proxy-go-ssl:
  nginx-proxy-go-acme:

networks:
  default:
    name: nginx-proxy
    external: true