version: '3.8'

services:
  nginx-proxy:
    image: shinde11/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    environment:
      NGINX_CONF_DIR: /etc/nginx
      CHALLENGE_DIR: /tmp/acme-challenges
      HOSTNAME: nginx-proxy
      GO_DEBUG_ENABLE: 'false'
      GO_DEBUG_PORT: '2345'
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./ssl/:/etc/ssl/:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  conf:
  vhost:
  html:
  dhparam:
  acme:
networks:
  default:
    external:
      name: nginx-proxy