name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.9"

      - name: Install Dependencies
        run: go mod download

      - name: Run Unit Tests
        run: go test ./...

  integration-tests:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.9"

      - name: Install Dependencies
        run: go mod download

      - name: Ensure Docker Daemon
        run: |
          docker version
          docker info

      - name: Pull Test Image
        run: docker pull nginx:1.27-alpine

      - name: Run Integration Tests
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
        run: go test -tags=integration ./...

